### ISSUE TITLE
[bench] 負荷レベルが最大まで上がるとクラッシュ

### ISSUE THREAD

**Issue by eagletmt** [isucon/isucon10-qualify#139]
スコアが `parameter.BoundaryOfLevel[11]` を超えると負荷レベルが 12 になり `parameter.ListOfIncWorkers[12]` を参照しようとするため、ベンチマーカの負荷レベルが最大まで上がると `panic: runtime error: index out of range [12] with length 12` でクラッシュしています。
https://github.com/isucon/isucon10-qualify/blob/2c037eb31539167b3d48bcd9ef660913b962868d/bench/scenario/load.go#L182

**Comment by mikiya771** [comment]
#140 で対応しました。ありがとうございます
