### ISSUE TITLE
[仕様相談] こだわり検索の想定解が見当たらない

### ISSUE THREAD

**Issue by mikiya771** [isucon/isucon10-qualify#57]
## 問題
こだわり条件検索を高速化する手段がない

## うまくいかない想定解（いずれも，ジェイウォーク自体の解決後を想定する)
それぞれの単一フィーチャーごとに，view countのパーシャルインデックスをはる
それぞれの単一フィーチャーごとの，それが存在するサブテーブルを作っておく

## うまくいかない理由
フィーチャーが増えるごとに，検索へのヒット数が減るという前提があるが，現状はフィーチャーの数を1-10の一様分布で決めている
ゆえに，検索条件が増えていってもかなりの数が検索結果として残ってしまい，インデックスが聞かない状態のOFFSETを強要され死んでしまう．

一様分布にしているコーど
https://github.com/isucon/isucon10-qualify/blob/f3ee1fc4e2021bb7920249c91d27c2b3a0394a3c/initial-data/make_chair_data.py#L155

## 改善案
上記のコードを変更して，イスがもつフィーチャーの種類数を少ない方に偏らせることが考えられる

**Comment by progfay** [comment]
検索時に最低 1 つ、最大で全種類を検索に入れていることも原因だと考えられる。

https://github.com/isucon/isucon10-qualify/blob/8f76177e38c7fbdc3fd159df3b84a2b6c792d6bf/bench/scenario/chairSearchScenario.go#L49-L53

このちょうどいい落とし所を決めてあげたい。

**Comment by progfay** [comment]
#71 による変更の結果、この問題が解消されたかを検証する必要がある
