### ISSUE TITLE
[bench] 最終的な実行結果を保存できるようにしたい

### ISSUE THREAD

**Issue by mikiya771** [isucon/isucon10-qualify#62]
現状標準出力に出しているが、証跡を残すために、実行結果をファイル名を指定してファイル出力できるようにしておきたい。
求める内容は2種類で、１つはErrの情報が全て乗っていること、もう一つは競技者に見せる結果と同じデータが入っていること。

**Comment by progfay** [comment]
これは bench-worker にて同様の処理を行い、 Portal に送信しているため、すでに実装されています！
